config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'hobby', to: 'static_pages#hobby'
  get 'about', to: 'static_pages#about'

  resources :articles do
  	resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
require "babosa"

class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
					  length: { minimum: 1}

	extend FriendlyId
  	friendly_id :title, use: :slugged

  	def normalize_friendly_id(input)
    	input.to_s.to_slug.normalize(transliterations: :ukrainian).to_s
  	end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	before_action :set_article, only: [:show, :edit, :update, :destroy]

	def index
		@articles = Article.all.order(created_at: :desc).paginate(page: params[:page], per_page: 5)
	end

	def show
		
	end

	def new
		@article = Article.new
	end

	def edit
		
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article.destroy

		redirect_to articles_path
	end

	def set_article
		@article = Article.friendly.find(params[:id])
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)	
		end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	before_action :set_article

	def create
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)

	end

	def set_article
		@article = Article.friendly.find(params[:article_id])
	end

	private 
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def hobby
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/_timestamp.erb
<i>Created: <%= obj.created_at.strftime('%B %e, %Y')%>
         <% if obj.created_at.strftime('%B %e, %Y') != obj.updated_at.strftime('%B %e, %Y') %>
          ; Update: <%= obj.updated_at.strftime('%B %e, %Y') %>
         <% end %></i>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>

<%= link_to 'Back to Weblog index', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
 
<p>There are <%= pluralize(Article.all.size, 'article') %> in this Weblog</p>

<p><%= link_to 'Create a new article', new_article_path %></p>
 
  <% @articles.each do |article| %>
    <div id='indexpost'>
      <H2><%= link_to article.title, article_path(article) %></H2>
      <p><%= render 'timestamp', obj: article%></p>
      <p><%= truncate(article.text, length: 100, separator: ' ') %></td>
      <p><%= link_to 'Show', article_path(article) %> 
      <%= link_to 'Edit', edit_article_path(article) %> 
      <%= link_to 'Delete', article_path(article), 
                                method: :delete, 
                                data: { confirm: 'Are you sure?'} %></p>
    </div>
  <% end %>

<div id='articles-pagination-container'><%= will_paginate @articles %></div>

<p>Return to <%= link_to 'Home page', root_path %></p>

app/views/articles/new.html.erb
<H1>New article</H1>

<%= render 'form' %>

<p><%= link_to "Back to Weblog index", articles_path %></p>

app/views/articles/show.html.erb
<H1>
  <%= @article.title %>
</H1>
<p><%= render 'timestamp', obj: @article %></p>
<p><%= link_to 'Edit the article', edit_article_path(@article) %> <%= link_to 'Delete the article', article_path(@article), method: :delete, data: { confirm: 'Are you sure?'}%></p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<p><%= link_to "Back to Weblog index", articles_path %></p>

app/views/comments/_comment.html.erb
<div id='comments-container'>
  <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
  </p>
   
  <p>
      <strong>Comment:</strong>
      <%= comment.body %>
  </p>

  <p>
  <%= link_to 'Delete the comment', [comment.article, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pws</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    	<%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/hobby.html.erb
<h1>StaticPages#hobby</h1>
<p>Find me in app/views/static_pages/hobby.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Welcome to My Personal Website</h1>

<p>Find my <%= link_to 'Weblog', controller: 'articles' %></p>